
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMA HOLA QUE TAL\n\tS : X QUE TAL\n\t\n\tX : HOLA Y\n\t\n\tY : COMA HOLA Y\n\t  | \n\t'
    
_lr_action_items = {'HOLA':([0,6,],[3,8,]),'$end':([1,7,],[0,-1,]),'QUE':([2,3,5,8,9,],[4,-4,-2,-4,-3,]),'COMA':([3,8,],[6,6,]),'TAL':([4,],[7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'X':([0,],[2,]),'Y':([3,8,],[5,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> X QUE TAL','S',3,'p_S','Test.py',47),
  ('X -> HOLA Y','X',2,'p_X','Test.py',53),
  ('Y -> COMA HOLA Y','Y',3,'p_Y','Test.py',58),
  ('Y -> <empty>','Y',0,'p_Y','Test.py',59),
]
